version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../allure-docker-service
      dockerfile: Dockerfile
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
    ports:
      - "4040:4040"
    volumes:
    - ./.data/allure-docker-service/allure-results:/app/allure-results